In [2]:
import numpy as np
import pandas as pd
from pandas import read_csv

In [3]:
ndarray=read_csv('Lecture 3-1 numpy exercise.csv').values

In [14]:
np.std(ndarray, axis=0)

array([1.35709204, 1.51350849, 1.4958247 , 1.40346054, 2.07293221,
       1.45391326, 1.26407973])

In [12]:
def calc_mean(ndarray):
    mu=np.mean(ndarray, axis=0)
    return mu
    
    

In [13]:
calc_mean(ndarray)

array([ 0.13845238,  0.15666667,  0.21464286, -0.13095238,  0.26142857,
       -0.09297619,  0.19690476])

In [15]:
def cal_std(ndarray):
    std=np.std(ndarray, axis=0)
    return std

In [16]:
cal_std(ndarray)

array([1.35709204, 1.51350849, 1.4958247 , 1.40346054, 2.07293221,
       1.45391326, 1.26407973])

In [49]:
def calc_cov(ndarray):
    cov=np.cov(ndarray, rowvar=False)
    return cov
    

In [50]:
pd.DataFrame(np.cov(ndarray, rowvar=False))

0         1         2         3         4         5         6
0  1.863888  0.781608  0.599049 -0.067928  0.691135  0.154075  0.481883
1  0.781608  2.318307  1.773359  0.432669  0.137480  0.479473  1.133609
2  0.599049  1.773359  2.264449  0.493860  0.035301  0.076854  1.127423
3 -0.067928  0.432669  0.493860  1.993433 -0.804589 -0.409582  0.302799
4  0.691135  0.137480  0.035301 -0.804589  4.348820  0.842109  0.436150
5  0.154075  0.479473  0.076854 -0.409582  0.842109  2.139332  0.117499
6  0.481883  1.133609  1.127423  0.302799  0.436150  0.117499  1.617149

In [69]:
w = np.array([0, 1, 0, 0, 0, 0, 0])

In [70]:
def port_mean(ndarray, w):
    mean=w.dot(calc_mean(ndarray).T)
    return mean

In [71]:
port_mean(ndarray, w)


0.15666666666666668

In [73]:
cal_std(ndarray)

array([1.35709204, 1.51350849, 1.4958247 , 1.40346054, 2.07293221,
       1.45391326, 1.26407973])

In [72]:
np.sqrt(w.dot(calc_cov(ndarray)).dot(w.T))

1.522598708560216